import type { Category, Task } from "./types";

export const sourceDocument = {
  title: "Full List Of Tasks - Respond CSM Comprehensive Operational Workflow Manual",
  url: "https://docs.google.com/document/d/1ymwzx6joQ2HoPnrnBxHNxL3F1T4J2DYbsqZGkiHV0Bs/edit?usp=sharing",
};

export const teamMembers = [
  "Unassigned",
  "Response CSM",
  "Account Manager",
  "Technical Admin",
  "Automation Specialist",
  "Voice AI Specialist",
  "Support Lead",
  "Accounts - Sandy",
  "Joseph",
  "Rich",
];

export const categories: Category[] = [
  { id: "accounts", name: "LaunchBay Accounts Stage Verification", phase: "Onboarding", accent: "#2563eb" },
  { id: "admin", name: "Admin & Account Setup", phase: "Onboarding", accent: "#0891b2" },
  { id: "welcome", name: "Welcome Onboarding Call", phase: "Onboarding", accent: "#0f766e" },
  { id: "crm", name: "Respond CRM Build", phase: "Build", accent: "#4f46e5" },
  { id: "automations", name: "Automations Configuration", phase: "Build", accent: "#7c3aed" },
  { id: "phone", name: "Phone & Voice AI Setup", phase: "Build", accent: "#ea580c" },
  { id: "testing", name: "Internal Testing Phase", phase: "Testing", accent: "#ca8a04" },
  { id: "wallet", name: "Go-Live CRM Configuration", phase: "Go-Live", accent: "#16a34a" },
  { id: "golive", name: "Go-Live Call", phase: "Go-Live", accent: "#059669" },
  { id: "stripe", name: "Post Go-Live Tracking & Stripe Verification", phase: "Post-Launch", accent: "#0284c7" },
  { id: "reporting", name: "Post Go-Live Reporting & Support", phase: "Post-Launch", accent: "#0d9488" },
  { id: "payments", name: "Ongoing Payment Support & Cancellations", phase: "Support", accent: "#b45309" },
  { id: "exit", name: "Client Exit & Account Finalization", phase: "Support", accent: "#64748b" },
];

const categoryMap = new Map(categories.map((category) => [category.id, category]));

function task(
  idNumber: number,
  categoryId: string,
  title: string,
  options: Partial<Omit<Task, "id" | "category" | "phase" | "title" | "sortOrder">> = {}
): Task {
  const category = categoryMap.get(categoryId);

  if (!category) {
    throw new Error(`Unknown category ${categoryId}`);
  }

  return {
    id: `rsp-${String(idNumber).padStart(3, "0")}`,
    title,
    category: category.name,
    phase: category.phase,
    status: options.status ?? "queued",
    assignee: options.assignee ?? "Unassigned",
    dueWindow: options.dueWindow ?? "",
    priority: options.priority ?? "normal",
    dependencies: options.dependencies ?? [],
    notes: options.notes ?? "",
    portalVisible: options.portalVisible ?? false,
    portalTitle: options.portalTitle ?? "",
    portalNote: options.portalNote ?? "",
    portalActionRequired: options.portalActionRequired ?? false,
    portalActionUrl: options.portalActionUrl ?? "",
    portalActionLabel: options.portalActionLabel ?? "",
    portalConfigured: options.portalConfigured ?? false,
    sortOrder: idNumber,
  };
}

export const seedTasks: Task[] = [
  task(1, "accounts", "Monitor the Accounts stage in LaunchBay to ensure the finance baseline is complete.", {
    status: "complete",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
    portalConfigured: true,
  }),
  task(2, "accounts", "Verify billing & Accounts stage complete in LaunchBay", {
    status: "complete",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
    notes: "Merged SOP steps:\n- Verify that Setup Fee Invoices Created and Sent is marked complete.\n- Verify that Setup Fee Paid and Reconciled is marked complete.\n- Check that SaaS Fees Are Activated.\n- Verify that Recurring Invoices Setup/Auto/Reconciled is completed.\n- Confirm Client Payments is marked as Active.",
    portalConfigured: true,
  }),
  task(7, "admin", "Set up & verify the LaunchBay–Slack Zapier sync", {
    status: "in_progress",
    assignee: "Response CSM",
    dueWindow: "Day 0",
    priority: "high",
    dependencies: ["rsp-002"],
    notes: "Merged SOP steps:\n- Set up the Zapier automation to sync the client's LaunchBay project with their Slack channel.\n- Verify Zapier successfully deployed the LaunchBay project and sent the welcome email.",
    portalConfigured: true,
  }),
  task(9, "admin", "Complete the Demo Task in the LaunchBay Accounts stage.", {
    assignee: "Response CSM",
    dueWindow: "Day 0",
    dependencies: ["rsp-007"],
    portalConfigured: true,
  }),
  task(10, "admin", "GHL logging & task-naming conventions", {
    status: "in_progress",
    assignee: "Response CSM",
    dueWindow: "Ongoing",
    priority: "high",
    notes: "Merged SOP steps:\n- Log every client interaction in GoHighLevel as an internal note formatted as Date - Reason - Name.\n- Create GHL tasks for all builds and support requests formatted as Client Name | Task Description.",
    portalConfigured: true,
  }),
  task(12, "welcome", "Ensure the client has submitted the onboarding form in LaunchBay to complete the onboarding milestone.", {
    status: "blocked",
    assignee: "Account Manager",
    dueWindow: "Day 1",
    priority: "critical",
    portalVisible: true,
    portalTitle: "Complete your onboarding form",
    portalNote: "Log in to your portal and submit the onboarding form before your Welcome Call.",
    portalActionRequired: true,
    portalConfigured: true,
  }),
  task(14, "welcome", "Run the Welcome Call & portal walkthrough", {
    assignee: "Account Manager",
    dueWindow: "Day 1",
    notes: "Merged SOP steps:\n- Present the TAI-Respond-Onboard slide deck to the client.\n- Create a copy of the AISS Client Artifact Template for meeting notes.",
    portalVisible: true,
    portalTitle: "Attend your Welcome Call & portal walkthrough",
    portalNote: "We'll walk you through your portal, your project milestones, and the messaging center on the call.",
    portalConfigured: true,
  }),
  task(15, "welcome", "Give the client their LaunchBay Magic Link and instruct them to bookmark it.", {
    assignee: "Response CSM",
    dueWindow: "Day 1",
    portalVisible: true,
    portalTitle: "Bookmark your portal link",
    portalNote: "Save your portal link so you can get back to it anytime.",
    portalActionRequired: true,
    portalConfigured: true,
  }),
  task(16, "welcome", "Review the onboarding form to collect business info, proof of address, and phone number preferences.", {
    assignee: "Response CSM",
    dueWindow: "Day 1",
    dependencies: ["rsp-012"],
    portalConfigured: true,
  }),
  task(17, "welcome", "Remind the client to complete the LaunchBay task to provide a CSV of their client database for importing.", {
    assignee: "Account Manager",
    dueWindow: "Day 1",
    priority: "high",
    portalVisible: true,
    portalTitle: "Upload your client database (CSV)",
    portalNote: "Prepare a CSV of your past customers and leads — we'll walk you through the upload.",
    portalActionRequired: true,
    portalConfigured: true,
  }),
  task(18, "welcome", "Define the AI pre-qualification questions and document them in green bold in the Artifact doc.", {
    assignee: "Response CSM",
    dueWindow: "Day 1",
    dependencies: ["rsp-014", "rsp-016"],
    portalVisible: true,
    portalTitle: "Review & approve your AI qualification questions",
    portalNote: "We'll go through your AI receptionist's qualifying questions together on the Welcome Call.",
    portalConfigured: true,
  }),
  task(19, "welcome", "Set expectations for the build timeline, 14 days to Go-Live, and when SaaS fees begin.", {
    assignee: "Account Manager",
    dueWindow: "Day 1",
    portalConfigured: true,
  }),
  task(20, "crm", "Deploy the Convert/Respond snapshot into the client's GHL sub-account.", {
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    priority: "high",
    dependencies: ["rsp-016"],
    portalConfigured: true,
  }),
  task(21, "crm", "Update the GHL Business Profile, including general info, rep info, and timezone.", {
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-020"],
    portalConfigured: true,
  }),
  task(22, "crm", "Add the client as a GHL user with limited permissions and no calendar access.", {
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-020"],
    portalConfigured: true,
  }),
  task(23, "crm", "Configure custom values & restrict the pipeline to inbound", {
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-018", "rsp-020"],
    notes: "Merged SOP steps:\n- Set custom values, including bot name and average opportunity value.\n- Restrict the pipeline to Inbound only.",
    portalConfigured: true,
  }),
  task(25, "crm", "Import the client contact database after CSV upload and mark the LaunchBay import task complete.", {
    status: "blocked",
    assignee: "Technical Admin",
    dueWindow: "Days 2-5",
    priority: "high",
    dependencies: ["rsp-017", "rsp-020"],
    portalConfigured: true,
  }),
  task(26, "automations", "Turn off all advanced Convert/Scale automations.", {
    assignee: "Automation Specialist",
    dueWindow: "Days 4-5",
    priority: "high",
    dependencies: ["rsp-020"],
    portalConfigured: true,
  }),
  task(27, "automations", "Keep AISS Inbound Lead Form Submitted in draft mode until Go-Live day.", {
    assignee: "Automation Specialist",
    dueWindow: "Days 4-5",
    priority: "critical",
    dependencies: ["rsp-026"],
    portalConfigured: true,
  }),
  task(28, "automations", "Publish only the designated Respond automations for forms, replies, pipeline updates, notifications, calls, transcripts, and coaching notes.", {
    assignee: "Automation Specialist",
    dueWindow: "Days 4-5",
    priority: "high",
    dependencies: ["rsp-026"],
    portalConfigured: true,
  }),
  task(29, "phone", "Submit ABN/ACN documents for Twilio Regulatory and Address Bundles.", {
    assignee: "Voice AI Specialist",
    dueWindow: "Days 4-6",
    priority: "critical",
    dependencies: ["rsp-016"],
    portalConfigured: true,
  }),
  task(30, "phone", "Purchase an SMS/MMS capable mobile number or manage the Porting stage in LaunchBay.", {
    status: "blocked",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 4-6",
    priority: "critical",
    dependencies: ["rsp-029"],
    portalConfigured: true,
  }),
  task(31, "phone", "Mark Procure & Submit Phone for Approval and Configure Phone Settings complete in LaunchBay.", {
    assignee: "Voice AI Specialist",
    dueWindow: "Days 4-6",
    dependencies: ["rsp-030"],
    portalConfigured: true,
  }),
  task(32, "phone", "Configure call routing, timeouts & forwarding", {
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-030", "rsp-022"],
    notes: "Merged SOP steps:\n- Set call routing priority: first to Client User, second blank, third to Voice AI Agent.\n- Set incoming call timeout to 7-10 seconds and outgoing call timeout to 20 seconds.\n- Set user forwarding settings to Web App & Mobile App.",
    portalConfigured: true,
  }),
  task(35, "phone", "Set recording notice & missed-call text-back", {
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-030"],
    notes: "Merged SOP steps:\n- Set the call recording text to exactly: Calls are recorded for quality purposes.\n- Turn on Missed Call Text Back and customize the greeting message.",
    portalConfigured: true,
  }),
  task(37, "phone", "Turn on Voice AI call transcription.", {
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-030"],
    portalConfigured: true,
  }),
  task(38, "phone", "Build the Voice AI knowledgebase & prompt", {
    status: "blocked",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    priority: "high",
    dependencies: ["rsp-016"],
    notes: "Merged SOP steps:\n- Crawl the client's website to generate the AI Knowledgebase.\n- Configure the Voice AI prompt to ask qualifying questions and offer a human callback instead of booking appointments.\n- Mark Configure AI Answering Service complete in LaunchBay.",
    portalConfigured: true,
  }),
  task(41, "testing", "Test the Voice AI call flow", {
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    priority: "high",
    dependencies: ["rsp-038"],
    notes: "Merged SOP steps:\n- Call the TradeAI number to verify the Voice AI agent picks up successfully.\n- Test the AI conversation to ensure it collects name, number, email, address, service, and urgency.\n- Verify the AI refuses appointment booking.",
    portalConfigured: true,
  }),
  task(44, "testing", "Verify transcripts, coaching notes & notifications", {
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    dependencies: ["rsp-037", "rsp-041"],
    notes: "Merged SOP steps:\n- Verify Call Transcript Note and Call Transcript Coaching Note generate in the GHL contact record.\n- Verify internal notification pings trigger correctly.",
    portalConfigured: true,
  }),
  task(46, "testing", "Final build check & notify the Account Manager", {
    assignee: "Response CSM",
    dueWindow: "Day 9",
    dependencies: ["rsp-041", "rsp-044"],
    notes: "Merged SOP steps:\n- Mark Perform Final Build Check complete in LaunchBay.\n- Complete the LaunchBay task to inform the Account Manager that AI is ready to launch.",
    portalConfigured: true,
  }),
  task(48, "testing", "Conduct the AI Testing Call with the client and mark it complete in LaunchBay.", {
    assignee: "Account Manager",
    dueWindow: "Days 9-10",
    dependencies: ["rsp-046"],
    portalVisible: true,
    portalTitle: "Test your AI receptionist live",
    portalNote: "On the AI Test Call we'll have you chat and speak with your AI to make sure it's ready to go.",
    portalConfigured: true,
  }),
  task(49, "testing", "Instruct the client to download the LeadConnector App before the go-live call and check off the corresponding task.", {
    assignee: "Account Manager",
    dueWindow: "Days 10-13",
    dependencies: ["rsp-048"],
    portalVisible: true,
    portalTitle: "Download the LeadConnector app",
    portalNote: "Search 'LeadConnector' in the App Store or Google Play and install it before your Go-Live call.",
    portalActionRequired: true,
    portalConfigured: true,
  }),
  task(50, "wallet", "Configure wallet auto-recharge ($100 / $10 threshold)", {
    assignee: "Technical Admin",
    dueWindow: "Day 13",
    dependencies: ["rsp-046"],
    notes: "Merged SOP steps:\n- Navigate to the client's GHL sub-account settings and open Billing.\n- Update Wallet Settings and turn auto-recharge on.\n- Set the wallet recharge amount to $100.\n- Set the wallet trigger threshold to $10.",
    portalConfigured: true,
  }),
  task(54, "wallet", "Enable SaaS subscription & set rebilling markup", {
    assignee: "Technical Admin",
    dueWindow: "Day 13",
    notes: "Merged SOP steps:\n- Navigate to GHL Agency View, Subaccounts, then Manage Client.\n- Confirm that the SaaS subscription plus Support has been turned on.\n- Set account rebilling markup fees to 2.5X on phone items and 3X on other items.",
    portalConfigured: true,
  }),
  task(57, "golive", "Turn AISS Inbound Lead Form Submitted from draft to on.", {
    assignee: "Automation Specialist",
    dueWindow: "Day 14",
    priority: "critical",
    dependencies: ["rsp-027", "rsp-048", "rsp-054"],
    portalConfigured: true,
  }),
  task(58, "golive", "Record the Go-Live call using Read.ai.", {
    assignee: "Account Manager",
    dueWindow: "Day 14",
    portalConfigured: true,
  }),
  task(59, "golive", "Demo the live system on the Go-Live call", {
    assignee: "Account Manager",
    dueWindow: "Day 14",
    dependencies: ["rsp-049"],
    notes: "Merged SOP steps:\n- Demo the LeadConnector App, including contacts, calls, SMS, push notifications, and wallet usage charges.\n- Demo the AI call summaries and coaching notes.\n- Demo a live missed call and the AI Answering Service picking up.",
    portalVisible: true,
    portalTitle: "Your Go-Live walkthrough",
    portalNote: "On the Go-Live call we'll show you how to handle calls, contacts, AI summaries, and notifications.",
    portalConfigured: true,
  }),
  task(62, "golive", "Get client permission to update their Website and Google Business Profile to the new TradeAI phone number.", {
    assignee: "Account Manager",
    dueWindow: "Day 14",
    priority: "high",
    dependencies: ["rsp-030"],
    portalVisible: true,
    portalTitle: "Approve updating your website & Google Business Profile",
    portalNote: "We'll switch your website and Google listing to your new AI phone number — we just need your go-ahead.",
    portalActionRequired: true,
    portalConfigured: true,
  }),
  task(63, "golive", "Mark Hold Go-Live call with client complete in LaunchBay.", {
    assignee: "Account Manager",
    dueWindow: "Day 14",
    dependencies: ["rsp-058", "rsp-059"],
    portalConfigured: true,
  }),
  task(64, "golive", "Send the post Go-Live LaunchBay message with the User Manual link, Read.ai recording link, and support instructions.", {
    assignee: "Response CSM",
    dueWindow: "Day 14",
    dependencies: ["rsp-063"],
    portalVisible: true,
    portalTitle: "You're live! Access your recording & support links",
    portalNote: "Your system is live. Check your portal messages for your call recording, user manual, and support resources.",
    portalConfigured: true,
  }),
  task(65, "stripe", "Verify billing is live in Stripe", {
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
    dependencies: ["rsp-063"],
    notes: "Merged SOP steps:\n- Log into Stripe and search for the client's company or customer name.\n- Verify that the monthly subscription is active and the client is successfully being billed.",
    portalConfigured: true,
  }),
  task(67, "stripe", "Update the Accounts sheet & notify Sandy", {
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
    notes: "Merged SOP steps:\n- Open the shared AISS Fees Summary for Accounts Google Sheet bookmarked in the accounts Slack channel.\n- Update the sheet with product name Respond, SaaS plan name, and SaaS fee in AUD including GST.\n- Change the client's status in the sheet to Live.\n- Send a message in the accounts Slack channel tagging Sandy that the client launched and fees are live.",
    portalConfigured: true,
  }),
  task(71, "stripe", "Monitor and check off LaunchBay countdown tasks for Monthly SaaS fees switched on at 14 days and 7 days.", {
    assignee: "Response CSM",
    dueWindow: "Days 14-21",
    dependencies: ["rsp-064"],
    portalConfigured: true,
  }),
  task(72, "reporting", "Complete Client Satisfaction Call and Send A Testimonial tasks in LaunchBay's Post Go-Live Check-in stage.", {
    assignee: "Account Manager",
    dueWindow: "Post Go-Live",
    dependencies: ["rsp-064"],
    portalVisible: true,
    portalTitle: "Share your experience — send us a testimonial",
    portalNote: "We'd love to hear how it's going. A short video or written testimonial means the world to us!",
    portalActionRequired: true,
    portalConfigured: true,
  }),
  task(73, "reporting", "Client check-in calls (weekly then monthly)", {
    assignee: "Account Manager",
    dueWindow: "Weeks 1-4",
    dependencies: ["rsp-064"],
    notes: "Merged SOP steps:\n- Conduct all four weekly client check-in calls and mark them complete sequentially in LaunchBay.\n- Transition to and conduct all three monthly client check-in calls, marking them complete in LaunchBay.",
    portalVisible: true,
    portalTitle: "Your check-in calls",
    portalNote: "We'll schedule regular check-ins to review performance and answer questions — we'll confirm times in your portal.",
    portalConfigured: true,
  }),
  task(75, "reporting", "Perform weekly GHL audits for calls, texts, transcriptions, and missed call AI answers.", {
    assignee: "Support Lead",
    dueWindow: "Weekly",
    dependencies: ["rsp-064"],
    portalConfigured: true,
  }),
  task(76, "reporting", "Provide Tier 1 support & escalate Tier 2 bugs", {
    assignee: "Support Lead",
    dueWindow: "Ongoing",
    dependencies: ["rsp-064"],
    notes: "Merged SOP steps:\n- Provide Tier 1 support via LaunchBay support request tickets and mark configurations and automations completed.\n- Escalate Tier 2 bugs to Joseph.",
    portalConfigured: true,
  }),
  task(78, "reporting", "Update the Monday KPI Active Clients Pipeline.", {
    assignee: "Response CSM",
    dueWindow: "Weekly",
    dependencies: ["rsp-064"],
    portalConfigured: true,
  }),
  task(79, "payments", "Field and resolve client support tickets regarding failed payments or billing questions.", {
    assignee: "Support Lead",
    dueWindow: "Ongoing",
    portalConfigured: true,
  }),
  task(80, "payments", "If client payment is late and needs chasing, coordinate with Sandy during Monday and Tuesday account coverage.", {
    assignee: "Accounts - Sandy",
    dueWindow: "As needed",
    priority: "high",
    dependencies: ["rsp-079"],
    portalConfigured: true,
  }),
  task(81, "payments", "If a client requests cancellation, pause, or downgrade, review the contract for the 9-month minimum term and escalate to Rich and Joseph before billing changes.", {
    assignee: "Support Lead",
    dueWindow: "As needed",
    priority: "critical",
    portalConfigured: true,
  }),
  task(82, "payments", "If an exit is approved, notify Accounts/Billing so the Stripe subscription and SaaS fees can be shut down.", {
    assignee: "Accounts - Sandy",
    dueWindow: "As needed",
    priority: "critical",
    dependencies: ["rsp-081"],
    portalConfigured: true,
  }),
  task(83, "exit", "Determine the real cancellation reason and attempt an intervention, such as a system walkthrough, before finalizing the exit pathway.", {
    assignee: "Rich",
    dueWindow: "As needed",
    priority: "critical",
    dependencies: ["rsp-081"],
    portalConfigured: true,
  }),
];
