import type { Category, Task } from "./types";

export const sourceDocument = {
  title: "Full List Of Tasks - Respond CSM Comprehensive Operational Workflow Manual",
  url: "https://docs.google.com/document/d/1ymwzx6joQ2HoPnrnBxHNxL3F1T4J2DYbsqZGkiHV0Bs/edit?usp=sharing",
};

export const teamMembers = [
  "Unassigned",
  "Response CSM",
  "Account Manager",
  "Technical Admin",
  "Automation Specialist",
  "Voice AI Specialist",
  "Support Lead",
  "Accounts - Sandy",
  "Joseph",
  "Rich",
];

export const categories: Category[] = [
  { id: "accounts", name: "LaunchBay Accounts Stage Verification", phase: "Onboarding", accent: "#2563eb" },
  { id: "admin", name: "Admin & Account Setup", phase: "Onboarding", accent: "#0891b2" },
  { id: "welcome", name: "Welcome Onboarding Call", phase: "Onboarding", accent: "#0f766e" },
  { id: "crm", name: "Respond CRM Build", phase: "Build", accent: "#4f46e5" },
  { id: "automations", name: "Automations Configuration", phase: "Build", accent: "#7c3aed" },
  { id: "phone", name: "Phone & Voice AI Setup", phase: "Build", accent: "#ea580c" },
  { id: "testing", name: "Internal Testing Phase", phase: "Testing", accent: "#ca8a04" },
  { id: "wallet", name: "Go-Live CRM Configuration", phase: "Go-Live", accent: "#16a34a" },
  { id: "golive", name: "Go-Live Call", phase: "Go-Live", accent: "#059669" },
  { id: "stripe", name: "Post Go-Live Tracking & Stripe Verification", phase: "Post-Launch", accent: "#0284c7" },
  { id: "reporting", name: "Post Go-Live Reporting & Support", phase: "Post-Launch", accent: "#0d9488" },
  { id: "payments", name: "Ongoing Payment Support & Cancellations", phase: "Support", accent: "#b45309" },
  { id: "exit", name: "Client Exit & Account Finalization", phase: "Support", accent: "#64748b" },
];

const categoryMap = new Map(categories.map((category) => [category.id, category]));

function task(
  idNumber: number,
  categoryId: string,
  title: string,
  options: Partial<Omit<Task, "id" | "category" | "phase" | "title" | "sortOrder">> = {}
): Task {
  const category = categoryMap.get(categoryId);

  if (!category) {
    throw new Error(`Unknown category ${categoryId}`);
  }

  return {
    id: `rsp-${String(idNumber).padStart(3, "0")}`,
    title,
    category: category.name,
    phase: category.phase,
    status: options.status ?? "queued",
    assignee: options.assignee ?? "Unassigned",
    dueWindow: options.dueWindow ?? "",
    priority: options.priority ?? "normal",
    dependencies: options.dependencies ?? [],
    notes: options.notes ?? "",
    portalVisible: options.portalVisible ?? false,
    portalTitle: options.portalTitle ?? "",
    portalNote: options.portalNote ?? "",
    portalActionRequired: options.portalActionRequired ?? false,
    portalActionUrl: options.portalActionUrl ?? "",
    portalActionLabel: options.portalActionLabel ?? "",
    portalConfigured: options.portalConfigured ?? false,
    sortOrder: idNumber,
  };
}

export const seedTasks: Task[] = [
  task(1, "accounts", "Monitor the Accounts stage in LaunchBay to ensure the finance baseline is complete.", {
    status: "complete",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
  }),
  task(2, "accounts", "Verify that Setup Fee Invoices Created and Sent is marked complete.", {
    status: "complete",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
  }),
  task(3, "accounts", "Verify that Setup Fee Paid and Reconciled is marked complete.", {
    status: "complete",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "critical",
    dependencies: ["rsp-002"],
  }),
  task(4, "accounts", "Check that SaaS Fees Are Activated.", {
    status: "complete",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
    dependencies: ["rsp-003"],
  }),
  task(5, "accounts", "Verify that Recurring Invoices Setup/Auto/Reconciled is completed.", {
    status: "review",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
    dependencies: ["rsp-004"],
  }),
  task(6, "accounts", "Confirm Client Payments is marked as Active.", {
    status: "review",
    assignee: "Accounts - Sandy",
    dueWindow: "Pre-build",
    priority: "high",
    dependencies: ["rsp-005"],
  }),
  task(7, "admin", "Set up the Zapier automation to sync the client's LaunchBay project with their Slack channel.", {
    status: "in_progress",
    assignee: "Response CSM",
    dueWindow: "Day 0",
    priority: "high",
    dependencies: ["rsp-006"],
  }),
  task(8, "admin", "Verify Zapier successfully deployed the LaunchBay project and sent the welcome email.", {
    status: "blocked",
    assignee: "Response CSM",
    dueWindow: "Day 0",
    priority: "high",
    dependencies: ["rsp-007"],
  }),
  task(9, "admin", "Complete the Demo Task in the LaunchBay Accounts stage.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 0",
    dependencies: ["rsp-008"],
  }),
  task(10, "admin", "Log every client interaction in GoHighLevel as an internal note formatted as Date - Reason - Name.", {
    status: "in_progress",
    assignee: "Response CSM",
    dueWindow: "Ongoing",
    priority: "high",
  }),
  task(11, "admin", "Create GHL tasks for all builds and support requests formatted as Client Name | Task Description.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Ongoing",
  }),
  task(12, "welcome", "Ensure the client has submitted the onboarding form in LaunchBay to complete the onboarding milestone.", {
    status: "blocked",
    assignee: "Account Manager",
    dueWindow: "Day 1",
    priority: "critical",
  }),
  task(13, "welcome", "Create a copy of the AISS Client Artifact Template for meeting notes.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 1",
    dependencies: ["rsp-012"],
  }),
  task(14, "welcome", "Present the TAI-Respond-Onboard slide deck to the client.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 1",
  }),
  task(15, "welcome", "Give the client their LaunchBay Magic Link and instruct them to bookmark it.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 1",
  }),
  task(16, "welcome", "Review the onboarding form to collect business info, proof of address, and phone number preferences.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 1",
    dependencies: ["rsp-012"],
  }),
  task(17, "welcome", "Remind the client to complete the LaunchBay task to provide a CSV of their client database for importing.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 1",
    priority: "high",
  }),
  task(18, "welcome", "Define the AI pre-qualification questions and document them in green bold in the Artifact doc.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 1",
    dependencies: ["rsp-013", "rsp-016"],
  }),
  task(19, "welcome", "Set expectations for the build timeline, 14 days to Go-Live, and when SaaS fees begin.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 1",
  }),
  task(20, "crm", "Deploy the Convert/Respond snapshot into the client's GHL sub-account.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    priority: "high",
    dependencies: ["rsp-016"],
  }),
  task(21, "crm", "Update the GHL Business Profile, including general info, rep info, and timezone.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-020"],
  }),
  task(22, "crm", "Add the client as a GHL user with limited permissions and no calendar access.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-020"],
  }),
  task(23, "crm", "Set custom values, including bot name and average opportunity value.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-018", "rsp-020"],
  }),
  task(24, "crm", "Restrict the pipeline to Inbound only.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Days 2-4",
    dependencies: ["rsp-020"],
  }),
  task(25, "crm", "Import the client contact database after CSV upload and mark the LaunchBay import task complete.", {
    status: "blocked",
    assignee: "Technical Admin",
    dueWindow: "Days 2-5",
    priority: "high",
    dependencies: ["rsp-017", "rsp-020"],
  }),
  task(26, "automations", "Turn off all advanced Convert/Scale automations.", {
    status: "queued",
    assignee: "Automation Specialist",
    dueWindow: "Days 4-5",
    priority: "high",
    dependencies: ["rsp-020"],
  }),
  task(27, "automations", "Keep AISS Inbound Lead Form Submitted in draft mode until Go-Live day.", {
    status: "queued",
    assignee: "Automation Specialist",
    dueWindow: "Days 4-5",
    priority: "critical",
    dependencies: ["rsp-026"],
  }),
  task(28, "automations", "Publish only the designated Respond automations for forms, replies, pipeline updates, notifications, calls, transcripts, and coaching notes.", {
    status: "queued",
    assignee: "Automation Specialist",
    dueWindow: "Days 4-5",
    priority: "high",
    dependencies: ["rsp-026"],
  }),
  task(29, "phone", "Submit ABN/ACN documents for Twilio Regulatory and Address Bundles.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 4-6",
    priority: "critical",
    dependencies: ["rsp-016"],
  }),
  task(30, "phone", "Purchase an SMS/MMS capable mobile number or manage the Porting stage in LaunchBay.", {
    status: "blocked",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 4-6",
    priority: "critical",
    dependencies: ["rsp-029"],
  }),
  task(31, "phone", "Mark Procure & Submit Phone for Approval and Configure Phone Settings complete in LaunchBay.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 4-6",
    dependencies: ["rsp-030"],
  }),
  task(32, "phone", "Set call routing priority: first to Client User, second blank, third to Voice AI Agent.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-030", "rsp-022"],
  }),
  task(33, "phone", "Set incoming call timeout to 7-10 seconds and outgoing call timeout to 20 seconds.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-032"],
  }),
  task(34, "phone", "Set user forwarding settings to Web App & Mobile App.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-022"],
  }),
  task(35, "phone", "Set the call recording text to exactly: Calls are recorded for quality purposes.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-030"],
  }),
  task(36, "phone", "Turn on Missed Call Text Back and customize the greeting message.", {
    status: "queued",
    assignee: "Automation Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-028", "rsp-030"],
  }),
  task(37, "phone", "Turn on Voice AI call transcription.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    dependencies: ["rsp-030"],
  }),
  task(38, "phone", "Crawl the client's website to generate the AI Knowledgebase.", {
    status: "blocked",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 5-7",
    priority: "high",
    dependencies: ["rsp-016"],
  }),
  task(39, "phone", "Configure the Voice AI prompt to ask qualifying questions and offer a human callback instead of booking appointments.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Days 6-7",
    priority: "high",
    dependencies: ["rsp-018", "rsp-038"],
  }),
  task(40, "phone", "Mark Configure AI Answering Service complete in LaunchBay.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Day 7",
    dependencies: ["rsp-039"],
  }),
  task(41, "testing", "Call the TradeAI number to verify the Voice AI agent picks up successfully.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    priority: "high",
    dependencies: ["rsp-040"],
  }),
  task(42, "testing", "Test the AI conversation to ensure it collects name, number, email, address, service, and urgency.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    priority: "high",
    dependencies: ["rsp-041"],
  }),
  task(43, "testing", "Verify the AI refuses appointment booking.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    priority: "high",
    dependencies: ["rsp-042"],
  }),
  task(44, "testing", "Verify Call Transcript Note and Call Transcript Coaching Note generate in the GHL contact record.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    dependencies: ["rsp-037", "rsp-042"],
  }),
  task(45, "testing", "Verify internal notification pings trigger correctly.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Days 7-9",
    dependencies: ["rsp-028", "rsp-042"],
  }),
  task(46, "testing", "Mark Perform Final Build Check complete in LaunchBay.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 9",
    dependencies: ["rsp-041", "rsp-042", "rsp-043", "rsp-044", "rsp-045"],
  }),
  task(47, "testing", "Complete the LaunchBay task to inform the Account Manager that AI is ready to launch.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 9",
    dependencies: ["rsp-046"],
  }),
  task(48, "testing", "Conduct the AI Testing Call with the client and mark it complete in LaunchBay.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Days 9-10",
    dependencies: ["rsp-047"],
  }),
  task(49, "testing", "Instruct the client to download the LeadConnector App before the go-live call and check off the corresponding task.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Days 10-13",
    dependencies: ["rsp-048"],
  }),
  task(50, "wallet", "Navigate to the client's GHL sub-account settings and open Billing.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Day 13",
    dependencies: ["rsp-046"],
  }),
  task(51, "wallet", "Update Wallet Settings and turn auto-recharge on.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Day 13",
    priority: "high",
    dependencies: ["rsp-050"],
  }),
  task(52, "wallet", "Set the wallet recharge amount to $100.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Day 13",
    dependencies: ["rsp-051"],
  }),
  task(53, "wallet", "Set the wallet trigger threshold to $10.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Day 13",
    dependencies: ["rsp-051"],
  }),
  task(54, "wallet", "Navigate to GHL Agency View, Subaccounts, then Manage Client.", {
    status: "queued",
    assignee: "Technical Admin",
    dueWindow: "Day 13",
  }),
  task(55, "wallet", "Confirm that the SaaS subscription plus Support has been turned on.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 13",
    priority: "critical",
    dependencies: ["rsp-054"],
  }),
  task(56, "wallet", "Set account rebilling markup fees to 2.5X on phone items and 3X on other items.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 13",
    priority: "critical",
    dependencies: ["rsp-055"],
  }),
  task(57, "golive", "Turn AISS Inbound Lead Form Submitted from draft to on.", {
    status: "queued",
    assignee: "Automation Specialist",
    dueWindow: "Day 14",
    priority: "critical",
    dependencies: ["rsp-027", "rsp-048", "rsp-056"],
  }),
  task(58, "golive", "Record the Go-Live call using Read.ai.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 14",
  }),
  task(59, "golive", "Demo the LeadConnector App, including contacts, calls, SMS, push notifications, and wallet usage charges.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 14",
    dependencies: ["rsp-049"],
  }),
  task(60, "golive", "Demo the AI call summaries and coaching notes.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 14",
    dependencies: ["rsp-044"],
  }),
  task(61, "golive", "Demo a live missed call and the AI Answering Service picking up.", {
    status: "queued",
    assignee: "Voice AI Specialist",
    dueWindow: "Day 14",
    dependencies: ["rsp-041", "rsp-057"],
  }),
  task(62, "golive", "Get client permission to update their Website and Google Business Profile to the new TradeAI phone number.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 14",
    priority: "high",
    dependencies: ["rsp-030"],
  }),
  task(63, "golive", "Mark Hold Go-Live call with client complete in LaunchBay.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Day 14",
    dependencies: ["rsp-058", "rsp-059", "rsp-060", "rsp-061"],
  }),
  task(64, "golive", "Send the post Go-Live LaunchBay message with the User Manual link, Read.ai recording link, and support instructions.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 14",
    dependencies: ["rsp-063"],
  }),
  task(65, "stripe", "Log into Stripe and search for the client's company or customer name.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
    dependencies: ["rsp-063"],
  }),
  task(66, "stripe", "Verify that the monthly subscription is active and the client is successfully being billed.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
    priority: "critical",
    dependencies: ["rsp-065"],
  }),
  task(67, "stripe", "Open the shared AISS Fees Summary for Accounts Google Sheet bookmarked in the accounts Slack channel.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
  }),
  task(68, "stripe", "Update the sheet with product name Respond, SaaS plan name, and SaaS fee in AUD including GST.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
    dependencies: ["rsp-067"],
  }),
  task(69, "stripe", "Change the client's status in the sheet to Live.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "Day 14",
    dependencies: ["rsp-068"],
  }),
  task(70, "stripe", "Send a message in the accounts Slack channel tagging Sandy that the client launched and fees are live.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Day 14",
    dependencies: ["rsp-069"],
  }),
  task(71, "stripe", "Monitor and check off LaunchBay countdown tasks for Monthly SaaS fees switched on at 14 days and 7 days.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Days 14-21",
    dependencies: ["rsp-064"],
  }),
  task(72, "reporting", "Complete Client Satisfaction Call and Send A Testimonial tasks in LaunchBay's Post Go-Live Check-in stage.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Post Go-Live",
    dependencies: ["rsp-064"],
  }),
  task(73, "reporting", "Conduct all four weekly client check-in calls and mark them complete sequentially in LaunchBay.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Weeks 1-4",
    dependencies: ["rsp-064"],
  }),
  task(74, "reporting", "Transition to and conduct all three monthly client check-in calls, marking them complete in LaunchBay.", {
    status: "queued",
    assignee: "Account Manager",
    dueWindow: "Months 2-4",
    dependencies: ["rsp-073"],
  }),
  task(75, "reporting", "Perform weekly GHL audits for calls, texts, transcriptions, and missed call AI answers.", {
    status: "queued",
    assignee: "Support Lead",
    dueWindow: "Weekly",
    dependencies: ["rsp-064"],
  }),
  task(76, "reporting", "Provide Tier 1 support via LaunchBay support request tickets and mark configurations and automations completed.", {
    status: "queued",
    assignee: "Support Lead",
    dueWindow: "Ongoing",
    dependencies: ["rsp-064"],
  }),
  task(77, "reporting", "Escalate Tier 2 bugs to Joseph.", {
    status: "queued",
    assignee: "Support Lead",
    dueWindow: "Ongoing",
    priority: "high",
  }),
  task(78, "reporting", "Update the Monday KPI Active Clients Pipeline.", {
    status: "queued",
    assignee: "Response CSM",
    dueWindow: "Weekly",
    dependencies: ["rsp-064"],
  }),
  task(79, "payments", "Field and resolve client support tickets regarding failed payments or billing questions.", {
    status: "queued",
    assignee: "Support Lead",
    dueWindow: "Ongoing",
  }),
  task(80, "payments", "If client payment is late and needs chasing, coordinate with Sandy during Monday and Tuesday account coverage.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "As needed",
    priority: "high",
    dependencies: ["rsp-079"],
  }),
  task(81, "payments", "If a client requests cancellation, pause, or downgrade, review the contract for the 9-month minimum term and escalate to Rich and Joseph before billing changes.", {
    status: "queued",
    assignee: "Support Lead",
    dueWindow: "As needed",
    priority: "critical",
  }),
  task(82, "payments", "If an exit is approved, notify Accounts/Billing so the Stripe subscription and SaaS fees can be shut down.", {
    status: "queued",
    assignee: "Accounts - Sandy",
    dueWindow: "As needed",
    priority: "critical",
    dependencies: ["rsp-081"],
  }),
  task(83, "exit", "Determine the real cancellation reason and attempt an intervention, such as a system walkthrough, before finalizing the exit pathway.", {
    status: "queued",
    assignee: "Rich",
    dueWindow: "As needed",
    priority: "critical",
    dependencies: ["rsp-081"],
  }),
];
