import type { RespondClient } from "./types";
import { seedTasks } from "./respondTasks";

export const missionTimelineDays = [
  "Jun 13",
  "Jun 14",
  "Jun 15",
  "Jun 16",
  "Jun 17",
  "Jun 18",
  "Jun 19",
  "Jun 20",
  "Jun 21",
  "Jun 22",
  "Jun 23",
  "Jun 24",
  "Jun 25",
  "Jun 26",
];

const baseRespondClients: Array<Omit<RespondClient, "environment" | "product">> = [
  {
    id: "northlane-health",
    name: "Northlane Health",
    code: "NH",
    industry: "Healthcare",
    owner: "Jamie Bennett",
    phase: "Onboarding",
    health: "off_track",
    progress: 34,
    currentTask: "Intake and discovery",
    goLiveDate: "2026-06-26",
    goLiveLabel: "Jun 26, 2026",
    lastUpdate: "Jun 13, 2026 9:12 AM",
    nextStep: "Intake call with client",
    blocker: "Waiting on client",
    risk: "high",
    activeTasks: 17,
    completedTasks: 8,
    timeline: [
      {
        label: "Intake and discovery",
        phase: "Onboarding",
        startDay: 0,
        span: 6,
        status: "off_track",
        marker: "risk",
      },
    ],
    attention: [
      {
        issue: "Onboarding stalled - intake incomplete",
        status: "Stalled onboarding",
        owner: "Jamie Bennett",
        lastUpdate: "Jun 13, 2026 9:12 AM",
        nextStep: "Intake call with client",
        blocker: "Waiting on client",
        risk: "high",
      },
    ],
  },
  {
    id: "pioneer-financial",
    name: "Pioneer Financial",
    code: "PF",
    industry: "Financial services",
    owner: "Taylor Kim",
    phase: "Implementation",
    health: "off_track",
    progress: 42,
    currentTask: "Phone numbers",
    goLiveDate: "2026-06-27",
    goLiveLabel: "Jun 27, 2026",
    lastUpdate: "Jun 13, 2026 8:47 AM",
    nextStep: "Twilio approval",
    blocker: "Twilio approval",
    risk: "high",
    activeTasks: 21,
    completedTasks: 15,
    timeline: [
      {
        label: "Phone numbers",
        phase: "Implementation",
        startDay: 1,
        span: 7,
        status: "off_track",
        marker: "approval",
      },
    ],
    attention: [
      {
        issue: "Active blocker: phone numbers",
        status: "Blocked",
        owner: "Taylor Kim",
        lastUpdate: "Jun 13, 2026 8:47 AM",
        nextStep: "Twilio approval",
        blocker: "Twilio approval",
        risk: "high",
      },
    ],
  },
  {
    id: "sunrise-retail",
    name: "Sunrise Retail",
    code: "SR",
    industry: "Retail",
    owner: "Avery Morgan",
    phase: "Implementation",
    health: "at_risk",
    progress: 58,
    currentTask: "CRM integration",
    goLiveDate: "2026-06-25",
    goLiveLabel: "Jun 25, 2026",
    lastUpdate: "Jun 12, 2026 4:33 PM",
    nextStep: "Dev fix and retest",
    blocker: "Engineering API fix",
    risk: "medium",
    activeTasks: 14,
    completedTasks: 22,
    timeline: [
      {
        label: "CRM integration",
        phase: "Implementation",
        startDay: 2,
        span: 8,
        status: "on_track",
        marker: "milestone",
      },
    ],
    attention: [
      {
        issue: "CRM integration failing tests",
        status: "Blocked",
        owner: "Avery Morgan",
        lastUpdate: "Jun 12, 2026 4:33 PM",
        nextStep: "Dev fix and retest",
        blocker: "Engineering API fix",
        risk: "medium",
      },
    ],
  },
  {
    id: "greenfield-insurance",
    name: "Greenfield Insurance",
    code: "GI",
    industry: "Insurance",
    owner: "Jordan Lee",
    phase: "Handoff",
    health: "on_track",
    progress: 72,
    currentTask: "Config handoff",
    goLiveDate: "2026-06-29",
    goLiveLabel: "Jun 29, 2026",
    lastUpdate: "Jun 13, 2026 10:03 AM",
    nextStep: "Handoff call at 1 PM",
    blocker: "Handoff to Support",
    risk: "medium",
    activeTasks: 10,
    completedTasks: 31,
    timeline: [
      {
        label: "Config handoff",
        phase: "Handoff",
        startDay: 1,
        span: 10,
        status: "at_risk",
        marker: "milestone",
      },
    ],
    attention: [
      {
        issue: "Ready for config handoff",
        status: "Handoff",
        owner: "Jordan Lee",
        lastUpdate: "Jun 13, 2026 10:03 AM",
        nextStep: "Handoff call at 1 PM",
        blocker: "Handoff to Support",
        risk: "medium",
      },
    ],
  },
  {
    id: "metro-logistics",
    name: "Metro Logistics",
    code: "ML",
    industry: "Logistics",
    owner: "Riley Patel",
    phase: "Implementation",
    health: "at_risk",
    progress: 49,
    currentTask: "Data access",
    goLiveDate: "2026-06-28",
    goLiveLabel: "Jun 28, 2026",
    lastUpdate: "Jun 13, 2026 9:58 AM",
    nextStep: "Client to grant access",
    blocker: "Waiting on client",
    risk: "medium",
    activeTasks: 18,
    completedTasks: 19,
    timeline: [
      {
        label: "Data access",
        phase: "Implementation",
        startDay: 0,
        span: 6,
        status: "at_risk",
        marker: "risk",
      },
    ],
    attention: [
      {
        issue: "Data access dependency",
        status: "Waiting",
        owner: "Riley Patel",
        lastUpdate: "Jun 13, 2026 9:58 AM",
        nextStep: "Client to grant access",
        blocker: "Waiting on client",
        risk: "medium",
      },
    ],
  },
  {
    id: "clearwater-dental",
    name: "Clearwater Dental",
    code: "CD",
    industry: "Dental",
    owner: "Taylor Kim",
    phase: "Implementation",
    health: "at_risk",
    progress: 53,
    currentTask: "Twilio numbers approval",
    goLiveDate: "2026-06-24",
    goLiveLabel: "Jun 24, 2026",
    lastUpdate: "Jun 13, 2026 9:05 AM",
    nextStep: "Twilio to approve",
    blocker: "Twilio approval",
    risk: "medium",
    activeTasks: 15,
    completedTasks: 18,
    timeline: [
      {
        label: "Twilio approval",
        phase: "Implementation",
        startDay: 2,
        span: 5,
        status: "at_risk",
        marker: "approval",
      },
    ],
    attention: [
      {
        issue: "Twilio numbers approval",
        status: "Approval",
        owner: "Taylor Kim",
        lastUpdate: "Jun 13, 2026 9:05 AM",
        nextStep: "Twilio to approve",
        blocker: "Twilio approval",
        risk: "medium",
      },
    ],
  },
  {
    id: "apex-staffing",
    name: "Apex Staffing",
    code: "AS",
    industry: "Staffing",
    owner: "Jamie Bennett",
    phase: "Testing",
    health: "on_hold",
    progress: 61,
    currentTask: "Duplicate task review",
    goLiveDate: "2026-07-01",
    goLiveLabel: "Jul 1, 2026",
    lastUpdate: "Jun 12, 2026 2:11 PM",
    nextStep: "Confirm and archive",
    blocker: "Duplicate workflow",
    risk: "low",
    activeTasks: 9,
    completedTasks: 24,
    timeline: [
      {
        label: "Duplicate task review",
        phase: "Testing",
        startDay: 4,
        span: 4,
        status: "on_hold",
      },
    ],
    attention: [
      {
        issue: "Suspected duplicate task",
        status: "Obsolete / duplicate",
        owner: "Jamie Bennett",
        lastUpdate: "Jun 12, 2026 2:11 PM",
        nextStep: "Confirm and archive",
        blocker: "None",
        risk: "low",
      },
    ],
  },
  {
    id: "bluepeak-manufacturing",
    name: "Bluepeak Manufacturing",
    code: "BM",
    industry: "Manufacturing",
    owner: "Avery Morgan",
    phase: "Testing",
    health: "off_track",
    progress: 46,
    currentTask: "UAT validation",
    goLiveDate: "2026-06-30",
    goLiveLabel: "Jun 30, 2026",
    lastUpdate: "Jun 13, 2026 8:22 AM",
    nextStep: "Escalate resourcing",
    blocker: "Multiple",
    risk: "high",
    activeTasks: 19,
    completedTasks: 16,
    timeline: [
      {
        label: "UAT validation",
        phase: "Testing",
        startDay: 3,
        span: 8,
        status: "off_track",
        marker: "risk",
      },
    ],
    attention: [
      {
        issue: "Go-live at risk",
        status: "At risk",
        owner: "Avery Morgan",
        lastUpdate: "Jun 13, 2026 8:22 AM",
        nextStep: "Escalate resourcing",
        blocker: "Multiple",
        risk: "high",
      },
    ],
  },
];

export const respondClients: RespondClient[] = baseRespondClients.map((client) => ({
  ...client,
  environment: "demo",
  product: "respond",
}));

export const liveRespondClients: RespondClient[] = [
  {
    id: "live-bruce-chaplin",
    environment: "live",
    product: "respond",
    name: "Bruce Chaplin",
    companyName: "BC TD Management PTY LTD",
    code: "BC",
    industry: "GHL Active Client",
    owner: "GHL import",
    phase: "Onboarding",
    health: "on_track",
    progress: 0,
    currentTask: "Fresh Respond onboarding template",
    goLiveDate: "2026-06-28",
    goLiveLabel: "Jun 28, 2026",
    lastUpdate: "Jun 14, 2026 5:20 AM",
    nextStep: "Start Respond onboarding checklist",
    blocker: "None",
    risk: "low",
    activeTasks: seedTasks.length,
    completedTasks: 0,
    timeline: [
      {
        label: "Respond checklist",
        phase: "Onboarding",
        startDay: 0,
        span: 5,
        status: "on_track",
        marker: "milestone",
      },
    ],
    attention: [
      {
        issue: "New client ready to start",
        status: "Ready",
        owner: "GHL import",
        lastUpdate: "Jun 14, 2026 5:20 AM",
        nextStep: "Start Respond onboarding checklist",
        blocker: "None",
        risk: "low",
      },
    ],
  },
];
