import type { RespondClient } from "./types";

export const scaleClients: RespondClient[] = [
  {
    id: "scale-northlane-health",
    environment: "demo",
    product: "scale",
    name: "Northlane Health",
    code: "NH",
    industry: "Healthcare",
    owner: "Scale CSM",
    phase: "Onboarding",
    health: "at_risk",
    progress: 18,
    currentTask: "Pre-onboarding and access collection",
    goLiveDate: "2026-07-14",
    goLiveLabel: "Jul 14, 2026",
    lastUpdate: "Jun 13, 2026 9:18 AM",
    nextStep: "Confirm access and onboarding assets",
    blocker: "Waiting on client access",
    risk: "medium",
    activeTasks: 307,
    completedTasks: 0,
    timeline: [
      {
        label: "Access and onboarding",
        phase: "Onboarding",
        startDay: 0,
        span: 5,
        status: "at_risk",
        marker: "approval",
      },
      {
        label: "Meta and Google strategy",
        phase: "Implementation",
        startDay: 5,
        span: 7,
        status: "on_track",
      },
    ],
    attention: [
      {
        issue: "Client access pack still incomplete",
        status: "Waiting",
        owner: "Scale CSM",
        lastUpdate: "Jun 13, 2026 9:18 AM",
        nextStep: "Request remaining logins and approvals",
        blocker: "Waiting on client access",
        risk: "medium",
      },
    ],
  },
  {
    id: "scale-pioneer-financial",
    environment: "demo",
    product: "scale",
    name: "Pioneer Financial",
    code: "PF",
    industry: "Financial services",
    owner: "Creative Strategist",
    phase: "Implementation",
    health: "off_track",
    progress: 27,
    currentTask: "Meta ads strategy and eBook build",
    goLiveDate: "2026-07-12",
    goLiveLabel: "Jul 12, 2026",
    lastUpdate: "Jun 13, 2026 8:42 AM",
    nextStep: "Approve campaign angle and offer",
    blocker: "Offer approval",
    risk: "high",
    activeTasks: 307,
    completedTasks: 0,
    timeline: [
      {
        label: "Meta offer and eBook",
        phase: "Implementation",
        startDay: 1,
        span: 8,
        status: "off_track",
        marker: "risk",
      },
    ],
    attention: [
      {
        issue: "Campaign offer approval holding creative build",
        status: "Blocked",
        owner: "Creative Strategist",
        lastUpdate: "Jun 13, 2026 8:42 AM",
        nextStep: "Get final approval from client",
        blocker: "Offer approval",
        risk: "high",
      },
    ],
  },
  {
    id: "scale-sunrise-retail",
    environment: "demo",
    product: "scale",
    name: "Sunrise Retail",
    code: "SR",
    industry: "Retail",
    owner: "Ads Team",
    phase: "Implementation",
    health: "on_track",
    progress: 39,
    currentTask: "Google Ads funnel creation",
    goLiveDate: "2026-07-16",
    goLiveLabel: "Jul 16, 2026",
    lastUpdate: "Jun 12, 2026 4:21 PM",
    nextStep: "Build landing page and tracking",
    blocker: "None",
    risk: "low",
    activeTasks: 307,
    completedTasks: 0,
    timeline: [
      {
        label: "Google funnel build",
        phase: "Implementation",
        startDay: 3,
        span: 8,
        status: "on_track",
        marker: "milestone",
      },
    ],
    attention: [
      {
        issue: "Landing page QA due before traffic handoff",
        status: "In progress",
        owner: "Ads Team",
        lastUpdate: "Jun 12, 2026 4:21 PM",
        nextStep: "Complete tracking QA",
        blocker: "None",
        risk: "low",
      },
    ],
  },
  {
    id: "scale-greenfield-insurance",
    environment: "demo",
    product: "scale",
    name: "Greenfield Insurance",
    code: "GI",
    industry: "Insurance",
    owner: "Automation Specialist",
    phase: "Testing",
    health: "at_risk",
    progress: 54,
    currentTask: "AI bot build and GHL configuration",
    goLiveDate: "2026-07-10",
    goLiveLabel: "Jul 10, 2026",
    lastUpdate: "Jun 13, 2026 10:03 AM",
    nextStep: "Finish AI test call script",
    blocker: "Calendar connection",
    risk: "medium",
    activeTasks: 307,
    completedTasks: 0,
    timeline: [
      {
        label: "AI bot and GHL config",
        phase: "Testing",
        startDay: 2,
        span: 7,
        status: "at_risk",
        marker: "approval",
      },
    ],
    attention: [
      {
        issue: "Calendar connection needed before AI test call",
        status: "Waiting",
        owner: "Automation Specialist",
        lastUpdate: "Jun 13, 2026 10:03 AM",
        nextStep: "Ask client to connect calendar",
        blocker: "Calendar connection",
        risk: "medium",
      },
    ],
  },
  {
    id: "scale-metro-logistics",
    environment: "demo",
    product: "scale",
    name: "Metro Logistics",
    code: "ML",
    industry: "Logistics",
    owner: "Voice AI Specialist",
    phase: "Go-Live",
    health: "on_track",
    progress: 68,
    currentTask: "AI test call and final checks",
    goLiveDate: "2026-07-08",
    goLiveLabel: "Jul 8, 2026",
    lastUpdate: "Jun 13, 2026 9:58 AM",
    nextStep: "Run final voice flow check",
    blocker: "None",
    risk: "low",
    activeTasks: 307,
    completedTasks: 0,
    timeline: [
      {
        label: "Final checks",
        phase: "Testing",
        startDay: 1,
        span: 5,
        status: "on_track",
      },
      {
        label: "Go-live call",
        phase: "Go-Live",
        startDay: 6,
        span: 3,
        status: "on_track",
        marker: "milestone",
      },
    ],
    attention: [
      {
        issue: "Final AI call QA scheduled",
        status: "Ready",
        owner: "Voice AI Specialist",
        lastUpdate: "Jun 13, 2026 9:58 AM",
        nextStep: "Complete call recording review",
        blocker: "None",
        risk: "low",
      },
    ],
  },
  {
    id: "scale-clearwater-dental",
    environment: "demo",
    product: "scale",
    name: "Clearwater Dental",
    code: "CD",
    industry: "Dental",
    owner: "Support Lead",
    phase: "Support",
    health: "on_hold",
    progress: 74,
    currentTask: "Post go-live reporting and admin",
    goLiveDate: "2026-07-04",
    goLiveLabel: "Jul 4, 2026",
    lastUpdate: "Jun 13, 2026 9:05 AM",
    nextStep: "Confirm reporting cadence",
    blocker: "Client paused reporting review",
    risk: "medium",
    activeTasks: 307,
    completedTasks: 0,
    timeline: [
      {
        label: "Post go-live reporting",
        phase: "Support",
        startDay: 3,
        span: 7,
        status: "on_hold",
      },
    ],
    attention: [
      {
        issue: "Reporting review paused by client",
        status: "On hold",
        owner: "Support Lead",
        lastUpdate: "Jun 13, 2026 9:05 AM",
        nextStep: "Reschedule reporting review",
        blocker: "Client paused reporting review",
        risk: "medium",
      },
    ],
  },
];
